# Generated by Django 5.1.6 on 2025-08-27 20:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pond",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=15)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="PondControl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("water_valve_state", models.BooleanField(default=False)),
                ("last_feed_time", models.DateTimeField(blank=True, null=True)),
                ("last_feed_amount", models.FloatField(blank=True, null=True)),
                (
                    "pond",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="controls",
                        to="ponds.pond",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PondPair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name for this pond pair (unique per user)",
                        max_length=30,
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        help_text="MAC address of the ESP32 device in format XX:XX:XX:XX:XX:XX",
                        max_length=17,
                        unique=True,
                        validators=[django.core.validators.MinLengthValidator(17)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pond_pairs_v2",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("owner", "name")},
            },
        ),
        migrations.AddField(
            model_name="pond",
            name="parent_pair",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ponds",
                to="ponds.pondpair",
            ),
        ),
        migrations.CreateModel(
            name="DeviceLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "log_type",
                    models.CharField(
                        choices=[
                            ("COMMAND", "Command"),
                            ("SENSOR", "Sensor Data"),
                            ("THRESHOLD", "Threshold Violation"),
                            ("AUTOMATION", "Automation"),
                            ("ERROR", "Error"),
                            ("INFO", "Information"),
                            ("WARNING", "Warning"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("success", models.BooleanField(default=True)),
                (
                    "command_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FEED", "Feed Command"),
                            ("WATER_DRAIN", "Drain Water"),
                            ("WATER_FILL", "Fill Water"),
                            ("FIRMWARE_UPDATE", "Firmware Update"),
                            ("RESTART", "Device Restart"),
                            ("CONFIG_UPDATE", "Configuration Update"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "command_id",
                    models.UUIDField(
                        blank=True,
                        help_text="Unique identifier for the command",
                        null=True,
                    ),
                ),
                ("error_code", models.CharField(blank=True, max_length=50, null=True)),
                ("error_details", models.TextField(blank=True, null=True)),
                (
                    "device_timestamp",
                    models.DateTimeField(
                        blank=True, help_text="Timestamp from the device", null=True
                    ),
                ),
                (
                    "firmware_version",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="device_logs_v2",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pond",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_logs",
                        to="ponds.pond",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["pond", "log_type"],
                        name="ponds_devic_pond_id_6cb474_idx",
                    ),
                    models.Index(
                        fields=["log_type", "success"],
                        name="ponds_devic_log_typ_c92467_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="ponds_devic_created_7df0d8_idx"
                    ),
                    models.Index(
                        fields=["command_id"], name="ponds_devic_command_60dec8_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parameter",
                    models.CharField(
                        choices=[
                            ("temperature", "Temperature"),
                            ("water_level", "Water Level"),
                            ("feed_level", "Feed Level"),
                            ("turbidity", "Turbidity"),
                            ("dissolved_oxygen", "Dissolved Oxygen"),
                            ("ph", "pH"),
                            ("ammonia", "Ammonia"),
                            ("battery", "Battery"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "alert_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("acknowledged", "Acknowledged"),
                            ("resolved", "Resolved"),
                            ("dismissed", "Dismissed"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("threshold_value", models.FloatField()),
                ("current_value", models.FloatField()),
                ("violation_count", models.IntegerField(default=1)),
                ("first_violation_at", models.DateTimeField(auto_now_add=True)),
                ("last_violation_at", models.DateTimeField(auto_now=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acknowledged_alerts_v2",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_alerts_v2",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pond",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="ponds.pond",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["pond", "status"], name="ponds_alert_pond_id_048462_idx"
                    ),
                    models.Index(
                        fields=["alert_level", "status"],
                        name="ponds_alert_alert_l_dd783f_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="ponds_alert_created_f7573c_idx"
                    ),
                ],
            },
        ),
        migrations.AlterUniqueTogether(
            name="pond",
            unique_together={("parent_pair", "name")},
        ),
        migrations.CreateModel(
            name="SensorData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "temperature",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(50),
                        ]
                    ),
                ),
                (
                    "water_level",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                (
                    "feed_level",
                    models.FloatField(
                        help_text="Percentage of feed remaining",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "turbidity",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1000),
                        ]
                    ),
                ),
                (
                    "dissolved_oxygen",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(20),
                        ]
                    ),
                ),
                (
                    "ph",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(14),
                        ]
                    ),
                ),
                (
                    "ammonia",
                    models.FloatField(
                        blank=True,
                        help_text="Ammonia level in mg/L",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "battery",
                    models.FloatField(
                        blank=True,
                        help_text="Battery level percentage",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "device_timestamp",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp from the device when reading was taken",
                        null=True,
                    ),
                ),
                (
                    "signal_strength",
                    models.IntegerField(
                        blank=True, help_text="WiFi signal strength in dBm", null=True
                    ),
                ),
                (
                    "pond",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sensor_readings",
                        to="ponds.pond",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["pond", "-timestamp"],
                        name="ponds_senso_pond_id_57e19f_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="ponds_senso_timesta_163d07_idx"
                    ),
                    models.Index(
                        fields=["device_timestamp"],
                        name="ponds_senso_device__690cf5_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SensorThreshold",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parameter",
                    models.CharField(
                        choices=[
                            ("temperature", "Temperature"),
                            ("water_level", "Water Level"),
                            ("feed_level", "Feed Level"),
                            ("turbidity", "Turbidity"),
                            ("dissolved_oxygen", "Dissolved Oxygen"),
                            ("ph", "pH"),
                            ("ammonia", "Ammonia"),
                            ("battery", "Battery"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "upper_threshold",
                    models.FloatField(
                        help_text="Upper threshold value for this parameter"
                    ),
                ),
                (
                    "lower_threshold",
                    models.FloatField(
                        help_text="Lower threshold value for this parameter"
                    ),
                ),
                (
                    "automation_action",
                    models.CharField(
                        choices=[
                            ("FEED", "Feed"),
                            ("WATER_DRAIN", "Drain Water"),
                            ("WATER_FILL", "Fill Water"),
                            ("ALERT", "Send Alert"),
                            ("NOTIFICATION", "Send Notification"),
                            ("LOG", "Log Event"),
                        ],
                        help_text="Action to take when threshold is violated",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "priority",
                    models.IntegerField(
                        default=1, help_text="Priority level (1=highest, 5=lowest)"
                    ),
                ),
                ("send_alert", models.BooleanField(default=True)),
                (
                    "alert_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                    ),
                ),
                (
                    "violation_timeout",
                    models.IntegerField(
                        default=30,
                        help_text="Seconds to wait before triggering action after threshold violation",
                    ),
                ),
                (
                    "max_violations",
                    models.IntegerField(
                        default=3,
                        help_text="Maximum violations before triggering action",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pond",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thresholds",
                        to="ponds.pond",
                    ),
                ),
            ],
            options={
                "ordering": ["priority", "parameter"],
                "indexes": [
                    models.Index(
                        fields=["pond", "parameter"],
                        name="ponds_senso_pond_id_6cfa93_idx",
                    ),
                    models.Index(
                        fields=["is_active", "priority"],
                        name="ponds_senso_is_acti_ad2e16_idx",
                    ),
                ],
                "unique_together": {("pond", "parameter")},
            },
        ),
    ]
