# Generated by Django 5.1.6 on 2025-08-29 21:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ponds", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pond",
            options={"ordering": ["id"]},
        ),
        migrations.AlterField(
            model_name="devicelog",
            name="command_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FEED", "Feed Command"),
                    ("WATER_DRAIN", "Drain Water"),
                    ("WATER_FILL", "Fill Water"),
                    ("WATER_FLUSH", "Flush Water"),
                    ("WATER_INLET_OPEN", "Open Water Inlet"),
                    ("WATER_INLET_CLOSE", "Close Water Inlet"),
                    ("WATER_OUTLET_OPEN", "Open Water Outlet"),
                    ("WATER_OUTLET_CLOSE", "Close Water Outlet"),
                    ("FIRMWARE_UPDATE", "Firmware Update"),
                    ("RESTART", "Device Restart"),
                    ("CONFIG_UPDATE", "Configuration Update"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sensorthreshold",
            name="automation_action",
            field=models.CharField(
                choices=[
                    ("FEED", "Feed"),
                    ("WATER_DRAIN", "Drain Water"),
                    ("WATER_FILL", "Fill Water"),
                    ("WATER_FLUSH", "Flush Water"),
                    ("WATER_INLET_OPEN", "Open Water Inlet"),
                    ("WATER_INLET_CLOSE", "Close Water Inlet"),
                    ("WATER_OUTLET_OPEN", "Open Water Outlet"),
                    ("WATER_OUTLET_CLOSE", "Close Water Outlet"),
                    ("ALERT", "Send Alert"),
                    ("NOTIFICATION", "Send Notification"),
                    ("LOG", "Log Event"),
                ],
                help_text="Action to take when threshold is violated",
                max_length=20,
            ),
        ),
    ]
