# Generated by Django 5.1.6 on 2025-10-03 21:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ponds", "0002_alter_pond_options_alter_devicelog_command_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # First, add the new fields to existing models
        migrations.AddField(
            model_name="pond",
            name="sensor_height",
            field=models.FloatField(
                default=50.0,
                help_text="Height of the sensor above the pond bottom in cm",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pond",
            name="tank_depth",
            field=models.FloatField(
                default=100.0,
                help_text="Total depth of the tank in cm",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pondpair",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Whether this pond pair is active"
            ),
        ),
        migrations.AddField(
            model_name="sensordata",
            name="pond_pair",
            field=models.ForeignKey(
                default=37,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sensor_data",
                to="ponds.pondpair",
            ),
            preserve_default=False,
        ),
        # Update existing fields
        migrations.AlterField(
            model_name="alert",
            name="acknowledged_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="acknowledged_alerts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="alert",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_alerts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="pondpair",
            name="device_id",
            field=models.CharField(
                help_text="MAC address of the ESP32 device in format XX:XX:XX:XX:XX:XX",
                max_length=17,
                validators=[django.core.validators.MinLengthValidator(17)],
            ),
        ),
        migrations.AlterField(
            model_name="pondpair",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pond_pairs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="sensordata",
            name="pond",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sensor_readings",
                to="ponds.pond",
            ),
        ),
        migrations.AlterField(
            model_name="sensordata",
            name="turbidity",
            field=models.FloatField(
                blank=True,
                help_text="Turbidity in NTU",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1000),
                ],
            ),
        ),
        # Add index
        migrations.AddIndex(
            model_name="sensordata",
            index=models.Index(
                fields=["pond_pair", "-timestamp"],
                name="ponds_senso_pond_pa_6b29de_idx",
            ),
        ),
        # Delete the old tables that are no longer needed
        migrations.DeleteModel(
            name="DeviceLog",
        ),
        migrations.DeleteModel(
            name="PondControl",
        ),
    ]
