# Generated by Django 5.1.6 on 2025-10-03 22:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ponds", "0003_auto_20251003_2258"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensordata",
            name="feed_level2",
            field=models.FloatField(
                blank=True,
                help_text="Second feed level sensor reading in percentage",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="sensordata",
            name="water_level2",
            field=models.FloatField(
                blank=True,
                help_text="Second water level sensor reading in percentage",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
