# Generated by Django 5.1.6 on 2025-10-04 19:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ponds", "0004_sensordata_feed_level2_sensordata_water_level2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sensordata",
            name="dissolved_oxygen",
            field=models.FloatField(
                blank=True,
                help_text="Dissolved oxygen in mg/L",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(20),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="sensordata",
            name="feed_level",
            field=models.FloatField(
                blank=True,
                help_text="Percentage of feed remaining",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="sensordata",
            name="ph",
            field=models.FloatField(
                blank=True,
                help_text="pH level",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(14),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="sensordata",
            name="temperature",
            field=models.FloatField(
                blank=True,
                help_text="Temperature in Celsius",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(50),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="sensordata",
            name="water_level",
            field=models.FloatField(
                blank=True,
                help_text="Water level percentage",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
