# Generated by Django 5.1.6 on 2025-08-24 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="APIVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=10, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deprecated", models.BooleanField(default=False)),
                ("deprecation_date", models.DateField(blank=True, null=True)),
                ("sunset_date", models.DateField(blank=True, null=True)),
                ("changelog", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-version"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "is_deprecated"],
                        name="api_apivers_is_acti_db466e_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="APIEndpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=255)),
                ("method", models.CharField(max_length=10)),
                ("is_active", models.BooleanField(default=True)),
                ("rate_limit", models.CharField(default="100/hour", max_length=50)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="endpoints",
                        to="api.apiversion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="APIUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True)),
                ("response_time", models.FloatField(blank=True, null=True)),
                ("status_code", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "endpoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage",
                        to="api.apiendpoint",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_usage",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="api_apiusag_user_id_4bf989_idx",
                    ),
                    models.Index(
                        fields=["endpoint", "created_at"],
                        name="api_apiusag_endpoin_4413d9_idx",
                    ),
                    models.Index(
                        fields=["status_code", "created_at"],
                        name="api_apiusag_status__bb1646_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="apiendpoint",
            index=models.Index(
                fields=["path", "method"], name="api_apiendp_path_4cfb5e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apiendpoint",
            index=models.Index(
                fields=["version", "is_active"], name="api_apiendp_version_f416b7_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="apiendpoint",
            unique_together={("path", "method", "version")},
        ),
    ]
