# Generated by Django 5.1.6 on 2025-02-15 21:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('device_id', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pond', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PondControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_valve_state', models.BooleanField(default=False)),
                ('last_feed_time', models.DateTimeField(blank=True, null=True)),
                ('last_feed_amount', models.FloatField(blank=True, null=True)),
                ('pond', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='controls', to='dashboard.pond')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('log_type', models.CharField(choices=[('INFO', 'Information'), ('ERROR', 'Error'), ('ACTION', 'Action')], max_length=6)),
                ('message', models.TextField()),
                ('pond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='dashboard.pond')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['pond', '-timestamp', 'log_type'], name='dashboard_d_pond_id_d58910_idx')],
            },
        ),
        migrations.CreateModel(
            name='AutomationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('automation_type', models.CharField(choices=[('FEED', 'Feeding'), ('WATER', 'Water Change')], max_length=5)),
                ('is_active', models.BooleanField(default=True)),
                ('time', models.TimeField()),
                ('days', models.CharField(max_length=13)),
                ('feed_amount', models.FloatField(blank=True, help_text='Feed amount in grams', null=True)),
                ('drain_water_level', models.FloatField(blank=True, help_text='Water level to drain to (currently hardcoded to 0%)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('target_water_level', models.FloatField(blank=True, help_text='Target water level percentage to refill to', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_schedules', to='dashboard.pond')),
            ],
            options={
                'ordering': ['time'],
                'indexes': [models.Index(fields=['pond', 'automation_type'], name='dashboard_a_pond_id_f5a668_idx')],
            },
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('temperature', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('water_level', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('turbidity', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('dissolved_oxygen', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('ph', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(14)])),
                ('pond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_readings', to='dashboard.pond')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['pond', '-timestamp'], name='dashboard_s_pond_id_510fa3_idx')],
            },
        ),
    ]
