# Generated by Django 5.1.6 on 2025-02-22 22:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_pond_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='feed_level',
            field=models.FloatField(default=0, help_text='Percentage of feed remaining', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
    ]
