"""
Django settings for FutureFish project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path
# from dotenv import load_dotenv  # Removed - using constants instead
from datetime import datetime, timedelta
import sys

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file 
# REMOVE IN PROD
# load_dotenv('.env.local')  # Removed - using constants instead

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-xi=pa7i9z)32y^#$a-qptt4$i0falvzsp6zah6opk*r^v&!xw=')

# System user for pond management
SYSTEM_USERNAME = os.getenv('SYSTEM_USERNAME', 'chief_fisherman')
SYSTEM_EMAIL = os.getenv('SYSTEM_EMAIL', 'info@futurefishagro.com')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True')  # Default to True in development

# Core constants (will be imported from core app in Phase 2)
DEVICE_ID_MIN_LENGTH = 17  # MAC address format: XX:XX:XX:XX:XX:XX
JWT_ACCESS_TOKEN_LIFETIME_DAYS = 60
JWT_REFRESH_TOKEN_LIFETIME_DAYS = 14
PASSWORD_MIN_LENGTH = 8
PASSWORD_MAX_LENGTH = 128
LOG_LEVEL = 'INFO'
LOG_FORMAT = '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
LOG_MAX_SIZE = 10 * 1024 * 1024  # 10MB
LOG_BACKUP_COUNT = 5
CACHE_TIMEOUT = 300  # 5 minutes
CACHE_KEY_PREFIX = 'futurefish'
API_VERSION = 'v1'
API_RATE_LIMIT = '100/hour'
DB_CONNECTION_TIMEOUT = 30
DB_QUERY_TIMEOUT = 60
CELERY_TASK_TIMEOUT = 300  # 5 minutes
CELERY_MAX_RETRIES = 3
CELERY_RETRY_DELAY = 60    # 1 minute

ALLOWED_HOSTS = [
    '*',
    'localhost', 
    '127.0.0.1',
    'app.futurefishagro.com',
    'futurefishagro.pythonanywhere.com',
    'future-fish-frontend.vercel.app',
    'https://49m2k272gx.eu-west-1.awsapprunner.com'
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "https://hoppscotch.io",
    "chrome-extension://amknoiejhlmhancpahfcfcfhllgkpbld",
    "https://49m2k272gx.eu-west-1.awsapprunner.com",
    "https://app.futurefishagro.com",
    "http://app.futurefishagro.com",
    "https://futurefishagro.pythonanywhere.com",
    "http://futurefishagro.pythonanywhere.com",
    "https://future-fish-frontend.vercel.app",
    "http://future-fish-frontend.vercel.app"
]

CSRF_TRUSTED_ORIGINS = [
    "https://49m2k272gx.eu-west-1.awsapprunner.com/",
    "https://hoppscotch.io",
    "chrome-extension://amknoiejhlmhancpahfcfcfhllgkpbld",
    "https://app.futurefishagro.com",
    "https://futurefishagro.pythonanywhere.com",
    "https://future-fish-frontend.vercel.app"
    "http://localhost:8000"
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = False
CORS_PREFLIGHT_MAX_AGE = 86400  # 24 hours

# Application definition

INSTALLED_APPS = [
    # Core apps
    'core',
    'ponds',
    'automation',
    'mqtt_client',
    'analytics',
    'users',
    'api',
    

    
    # Django apps
    'asgiref',
    'corsheaders',
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_simplejwt.token_blacklist',
    'drf_spectacular',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',
        'user': '1000/hour'
    },
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# Update ASGI application
ASGI_APPLICATION = 'FutureFish.asgi.application'

# Development-specific settings
if DEBUG:
    # Show full exception information in development
    import logging
    logging.getLogger('django.db.backends').setLevel(logging.DEBUG)

# Async settings
# DJANGO_ALLOW_ASYNC_UNSAFE = True  # Only for development

# JWT Settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=JWT_ACCESS_TOKEN_LIFETIME_DAYS),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=JWT_REFRESH_TOKEN_LIFETIME_DAYS),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

MIDDLEWARE = [
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # Comment out CSRF for API endpoints
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Add debug middleware in development
if DEBUG:
    MIDDLEWARE.append('django.middleware.common.BrokenLinkEmailsMiddleware')

ROOT_URLCONF = 'FutureFish.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'FutureFish.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': 'db.sqlite3',
        'OPTIONS': {
            'timeout': DB_QUERY_TIMEOUT,
        },
        'CONN_MAX_AGE': DB_CONNECTION_TIMEOUT,
    }
}

# Test database configuration
if 'test' in sys.argv:
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': ':memory:',  # Use in-memory database for tests
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': PASSWORD_MIN_LENGTH,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = "Africa/Lagos"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Make sure to create the staticfiles directory as well
os.makedirs(STATIC_ROOT, exist_ok=True)
os.makedirs(os.path.join(BASE_DIR, 'static', 'dist'), exist_ok=True)

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': LOG_FORMAT,
        },
        'simple': {
            'format': '{asctime} - {name} - {levelname} - {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': LOG_LEVEL,
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'django.log'),
            'maxBytes': LOG_MAX_SIZE,
            'backupCount': LOG_BACKUP_COUNT,
            'formatter': 'verbose',
        },
        'console': {
            'level': 'INFO',  # Show info, warnings, and errors in console
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': LOG_LEVEL,
    },
    'loggers': {
        # Django core logging
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        # HTTP request logging
        'django.server': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        # Database queries (very useful for debugging)
        'django.db.backends': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        # Authentication logging
        'django.security': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        # Your app-specific loggers
        'automation': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'mqtt_client': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'ponds': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'users': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        # REST framework logging
        'rest_framework': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

# Create logs directory
os.makedirs(os.path.join(BASE_DIR, 'logs'), exist_ok=True)

# Spectacular (Swagger) Settings
# Import Swagger/OpenAPI Documentation Settings
from ..swagger_config import get_spectacular_settings

# Swagger/OpenAPI Documentation Settings
SPECTACULAR_SETTINGS = get_spectacular_settings('development')

# Cache configuration
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
        'TIMEOUT': CACHE_TIMEOUT,
        'KEY_PREFIX': CACHE_KEY_PREFIX,
    }
}

# Celery configuration
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TIME_LIMIT = CELERY_TASK_TIMEOUT
CELERY_TASK_SOFT_TIME_LIMIT = CELERY_TASK_TIMEOUT - 30
CELERY_TASK_MAX_RETRIES = CELERY_MAX_RETRIES
CELERY_TASK_RETRY_DELAY = CELERY_RETRY_DELAY
