"""
Django settings for FutureFish project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path
from decouple import config
from datetime import datetime, timedelta
import sys

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file 
# REMOVE IN PROD
# load_dotenv('.env.local')  # Removed - using constants instead

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-xi=pa7i9z)32y^#$a-qptt4$i0falvzsp6zah6opk*r^v&!xw=')

# System user for pond management
SYSTEM_USERNAME = config('SYSTEM_USERNAME', default='chief_fisherman')
SYSTEM_EMAIL = config('SYSTEM_EMAIL', default='info@futurefishagro.com')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

# Core constants - now using environment variables
DEVICE_ID_MIN_LENGTH = config('DEVICE_ID_MIN_LENGTH', default=17, cast=int)
JWT_ACCESS_TOKEN_LIFETIME_DAYS = config('JWT_ACCESS_TOKEN_LIFETIME_DAYS', default=60, cast=int)
JWT_REFRESH_TOKEN_LIFETIME_DAYS = config('JWT_REFRESH_TOKEN_LIFETIME_DAYS', default=14, cast=int)
PASSWORD_MIN_LENGTH = config('PASSWORD_MIN_LENGTH', default=8, cast=int)
PASSWORD_MAX_LENGTH = config('PASSWORD_MAX_LENGTH', default=128, cast=int)
LOG_LEVEL = config('LOG_LEVEL', default='INFO')
LOG_FORMAT = config('LOG_FORMAT', default='%(asctime)s - %(name)s - %(levelname)s - %(message)s')
LOG_MAX_SIZE = config('LOG_MAX_SIZE', default=10485760, cast=int)  # 10MB
LOG_BACKUP_COUNT = config('LOG_BACKUP_COUNT', default=5, cast=int)
CACHE_TIMEOUT = config('CACHE_TIMEOUT', default=300, cast=int)  # 5 minutes
CACHE_KEY_PREFIX = config('CACHE_KEY_PREFIX', default='futurefish')
API_VERSION = config('API_VERSION', default='v1')
API_RATE_LIMIT = config('API_RATE_LIMIT', default='100/hour')
DB_CONNECTION_TIMEOUT = config('DB_CONNECTION_TIMEOUT', default=30, cast=int)
DB_QUERY_TIMEOUT = config('DB_QUERY_TIMEOUT', default=60, cast=int)
CELERY_TASK_TIMEOUT = config('CELERY_TASK_TIMEOUT', default=300, cast=int)  # 5 minutes
CELERY_MAX_RETRIES = config('CELERY_MAX_RETRIES', default=3, cast=int)
CELERY_RETRY_DELAY = config('CELERY_RETRY_DELAY', default=60, cast=int)    # 1 minute

ALLOWED_HOSTS = [
    '*',
    'localhost', 
    '127.0.0.1',
    'app.futurefishagro.com',
    'futurefishagro.pythonanywhere.com',
    'future-fish-frontend.vercel.app',
    '.railway.app',
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "https://hoppscotch.io",
    "chrome-extension://amknoiejhlmhancpahfcfcfhllgkpbld",
    "https://49m2k272gx.eu-west-1.awsapprunner.com",
    "https://app.futurefishagro.com",
    "http://app.futurefishagro.com",
    "https://futurefishagro.pythonanywhere.com",
    "http://futurefishagro.pythonanywhere.com",
    "https://future-fish-frontend.vercel.app",
    "http://future-fish-frontend.vercel.app"
]

CSRF_TRUSTED_ORIGINS = [
    "https://49m2k272gx.eu-west-1.awsapprunner.com/",
    "https://hoppscotch.io",
    "chrome-extension://amknoiejhlmhancpahfcfcfhllgkpbld",
    "https://app.futurefishagro.com",
    "https://futurefishagro.pythonanywhere.com",
    "https://future-fish-frontend.vercel.app"
    "http://localhost:8000"
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = False
CORS_PREFLIGHT_MAX_AGE = config('CORS_PREFLIGHT_MAX_AGE', default=86400, cast=int)  # 24 hours

# Application definition

INSTALLED_APPS = [
    # Core apps
    'core',
    'ponds',
    'automation',
    'mqtt_client',
    'analytics',
    'users',
    'api',
    'qr_generator',
    

    
    # Django apps
    'asgiref',
    'corsheaders',
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_simplejwt.token_blacklist',
    'drf_spectacular',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Celery apps
    'django_celery_beat',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': config('API_DEFAULT_PAGE_SIZE', default=50, cast=int),
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': config('API_RATE_LIMIT_ANON', default='100/hour'),
        'user': config('API_RATE_LIMIT_USER', default='1000/hour')
    },
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# Update ASGI application
ASGI_APPLICATION = 'FutureFish.asgi.application'

# Development-specific settings
if DEBUG:
    # Show full exception information in development
    import logging
    logging.getLogger('django.db.backends').setLevel(logging.DEBUG)

# Async settings
# DJANGO_ALLOW_ASYNC_UNSAFE = True  # Only for development

# JWT Settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=JWT_ACCESS_TOKEN_LIFETIME_DAYS),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=JWT_REFRESH_TOKEN_LIFETIME_DAYS),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

MIDDLEWARE = [
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # Comment out CSRF for API endpoints
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Add debug middleware in development
if DEBUG:
    MIDDLEWARE.append('django.middleware.common.BrokenLinkEmailsMiddleware')

ROOT_URLCONF = 'FutureFish.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'FutureFish.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': 'db.sqlite3',
        'OPTIONS': {
            'timeout': DB_QUERY_TIMEOUT,
        },
        'CONN_MAX_AGE': DB_CONNECTION_TIMEOUT,
    }
}

# Test database configuration
if 'test' in sys.argv:
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': ':memory:',  # Use in-memory database for tests
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': PASSWORD_MIN_LENGTH,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = "Africa/Lagos"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Media files (User uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Make sure to create the staticfiles and media directories
os.makedirs(STATIC_ROOT, exist_ok=True)
os.makedirs(MEDIA_ROOT, exist_ok=True)
os.makedirs(os.path.join(BASE_DIR, 'static', 'dist'), exist_ok=True)
os.makedirs(os.path.join(MEDIA_ROOT, 'qr_generator', 'uploads'), exist_ok=True)
os.makedirs(os.path.join(MEDIA_ROOT, 'qr_generator', 'qr_codes'), exist_ok=True)

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': LOG_FORMAT,
        },
        'simple': {
            'format': '{asctime} - {name} - {levelname} - {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': LOG_LEVEL,
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'django.log'),
            'maxBytes': LOG_MAX_SIZE,
            'backupCount': LOG_BACKUP_COUNT,
            'formatter': 'verbose',
        },
        'console': {
            'level': 'INFO',  # Show info, warnings, and errors in console
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': LOG_LEVEL,
    },
    'loggers': {
        # Django core logging
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        # HTTP request logging
        'django.server': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        # Database queries (very useful for debugging)
        'django.db.backends': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        # Authentication logging
        'django.security': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        # Your app-specific loggers
        'automation': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'mqtt_client': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'ponds': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'users': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        # REST framework logging
        'rest_framework': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

# Create logs directory
os.makedirs(os.path.join(BASE_DIR, 'logs'), exist_ok=True)

# Spectacular (Swagger) Settings
# Import Swagger/OpenAPI Documentation Settings
from ..swagger_config import get_spectacular_settings

# Swagger/OpenAPI Documentation Settings
SPECTACULAR_SETTINGS = get_spectacular_settings('development')

# Cache configuration
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
        'TIMEOUT': config('CACHE_TIMEOUT', default=300, cast=int),
        'KEY_PREFIX': config('CACHE_KEY_PREFIX', default='futurefish'),
    }
}

# Celery configuration
CELERY_BROKER_URL = config('CELERY_BROKER_URL', default='redis://localhost:6379/0')
CELERY_RESULT_BACKEND = config('CELERY_RESULT_BACKEND', default='redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TIME_LIMIT = CELERY_TASK_TIMEOUT
CELERY_TASK_SOFT_TIME_LIMIT = CELERY_TASK_TIMEOUT - 30
CELERY_TASK_MAX_RETRIES = CELERY_MAX_RETRIES
CELERY_TASK_RETRY_DELAY = CELERY_RETRY_DELAY

# Celery Beat Schedule Intervals (seconds)
CELERY_HANDLE_COMMAND_TIMEOUTS_INTERVAL = config('CELERY_HANDLE_COMMAND_TIMEOUTS_INTERVAL', default=30, cast=int)
CELERY_SYNC_DEVICE_STATUS_INTERVAL = config('CELERY_SYNC_DEVICE_STATUS_INTERVAL', default=60, cast=int)
CELERY_CLEANUP_OLD_MQTT_MESSAGES_INTERVAL = config('CELERY_CLEANUP_OLD_MQTT_MESSAGES_INTERVAL', default=3600, cast=int)
CELERY_MONITOR_MQTT_BRIDGE_HEALTH_INTERVAL = config('CELERY_MONITOR_MQTT_BRIDGE_HEALTH_INTERVAL', default=300, cast=int)
CELERY_CLEANUP_STUCK_AUTOMATIONS_INTERVAL = config('CELERY_CLEANUP_STUCK_AUTOMATIONS_INTERVAL', default=900, cast=int)
CELERY_CHECK_SCHEDULED_AUTOMATIONS_INTERVAL = config('CELERY_CHECK_SCHEDULED_AUTOMATIONS_INTERVAL', default=60, cast=int)
CELERY_PROCESS_THRESHOLD_VIOLATIONS_INTERVAL = config('CELERY_PROCESS_THRESHOLD_VIOLATIONS_INTERVAL', default=30, cast=int)

# Celery Task Routing
CELERY_TASK_ROUTES = {
    'automation.tasks.*': {'queue': 'automation'},
    'mqtt_client.tasks.*': {'queue': 'mqtt'},
    'analytics.tasks.*': {'queue': 'analytics'},
}

# Celery Worker Settings
CELERY_WORKER_CONCURRENCY = 1  # Limit to 1 worker for SQLite compatibility
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_WORKER_MAX_TASKS_PER_CHILD = 1000

# Celery Task Settings
CELERY_TASK_ALWAYS_EAGER = False  # Set to True for testing
CELERY_TASK_EAGER_PROPAGATES = True

# Celery Result Backend Settings
CELERY_RESULT_EXPIRES = 3600  # 1 hour

# Celery Beat Schedule
CELERY_BEAT_SCHEDULE = {
    'handle-command-timeouts': {
        'task': 'mqtt_client.tasks.handle_command_timeouts',
        'schedule': CELERY_HANDLE_COMMAND_TIMEOUTS_INTERVAL,
    },
    'sync-device-status-from-mqtt': {
        'task': 'mqtt_client.tasks.sync_device_status_from_mqtt',
        'schedule': CELERY_SYNC_DEVICE_STATUS_INTERVAL,
    },
    'cleanup-old-mqtt-messages': {
        'task': 'mqtt_client.tasks.cleanup_old_mqtt_messages',
        'schedule': CELERY_CLEANUP_OLD_MQTT_MESSAGES_INTERVAL,
    },
    'monitor-mqtt-bridge-health': {
        'task': 'mqtt_client.tasks.monitor_mqtt_bridge_health',
        'schedule': CELERY_MONITOR_MQTT_BRIDGE_HEALTH_INTERVAL,
    },
    'cleanup-stuck-automations': {
        'task': 'mqtt_client.tasks.cleanup_stuck_automations',
        'schedule': CELERY_CLEANUP_STUCK_AUTOMATIONS_INTERVAL,
    },
    'check-scheduled-automations': {
        'task': 'automation.tasks.check_scheduled_automations',
        'schedule': CELERY_CHECK_SCHEDULED_AUTOMATIONS_INTERVAL,
    },
    'process-threshold-violations': {
        'task': 'automation.tasks.process_threshold_violations',
        'schedule': CELERY_PROCESS_THRESHOLD_VIOLATIONS_INTERVAL,
    },
}

# MQTT Configuration
MQTT_BROKER_HOST = config('MQTT_BROKER_HOST', default='broker.emqx.io')
MQTT_BROKER_PORT = config('MQTT_BROKER_PORT', default=1883, cast=int)
MQTT_KEEPALIVE = config('MQTT_KEEPALIVE', default=60, cast=int)
MQTT_TIMEOUT = config('MQTT_TIMEOUT', default=10, cast=int)
MQTT_USERNAME = config('MQTT_USERNAME', default='futurefish_backend')
MQTT_PASSWORD = config('MQTT_PASSWORD', default='7-33@98:epY}')
MQTT_USE_TLS = config('MQTT_USE_TLS', default=False, cast=bool)

# Device Command Settings
DEVICE_COMMAND_TIMEOUT_SECONDS = config('DEVICE_COMMAND_TIMEOUT_SECONDS', default=10, cast=int)
DEVICE_COMMAND_MAX_RETRIES = config('DEVICE_COMMAND_MAX_RETRIES', default=3, cast=int)
DEVICE_COMMAND_RETRY_DELAY = config('DEVICE_COMMAND_RETRY_DELAY', default=60, cast=int)
DEVICE_HEARTBEAT_OFFLINE_THRESHOLD = config('DEVICE_HEARTBEAT_OFFLINE_THRESHOLD', default=30, cast=int)
DEVICE_HEARTBEAT_CHECK_INTERVAL = config('DEVICE_HEARTBEAT_CHECK_INTERVAL', default=10, cast=int)

# Automation Settings
AUTOMATION_MAX_EXECUTION_TIME_HOURS = config('AUTOMATION_MAX_EXECUTION_TIME_HOURS', default=2, cast=int)
AUTOMATION_RETRY_DELAY_MINUTES = config('AUTOMATION_RETRY_DELAY_MINUTES', default=1, cast=int)
AUTOMATION_DEFAULT_THRESHOLD_TIMEOUT = config('AUTOMATION_DEFAULT_THRESHOLD_TIMEOUT', default=30, cast=int)
AUTOMATION_MAX_THRESHOLD_VIOLATIONS = config('AUTOMATION_MAX_THRESHOLD_VIOLATIONS', default=3, cast=int)
AUTOMATION_DEFAULT_FEED_AMOUNT = config('AUTOMATION_DEFAULT_FEED_AMOUNT', default=100, cast=int)
AUTOMATION_MAX_FEED_AMOUNT = config('AUTOMATION_MAX_FEED_AMOUNT', default=1000, cast=int)
AUTOMATION_MIN_FEED_AMOUNT = config('AUTOMATION_MIN_FEED_AMOUNT', default=10, cast=int)
AUTOMATION_DEFAULT_WATER_LEVEL = config('AUTOMATION_DEFAULT_WATER_LEVEL', default=80, cast=int)
AUTOMATION_MIN_WATER_LEVEL = config('AUTOMATION_MIN_WATER_LEVEL', default=20, cast=int)
AUTOMATION_MAX_WATER_LEVEL = config('AUTOMATION_MAX_WATER_LEVEL', default=100, cast=int)
AUTOMATION_DEFAULT_SENSOR_HEIGHT = config('AUTOMATION_DEFAULT_SENSOR_HEIGHT', default=50.0, cast=float)
AUTOMATION_DEFAULT_TANK_DEPTH = config('AUTOMATION_DEFAULT_TANK_DEPTH', default=100.0, cast=float)

# Data Cleanup Settings
MQTT_MESSAGE_RETENTION_DAYS = config('MQTT_MESSAGE_RETENTION_DAYS', default=30, cast=int)
AUTOMATION_CLEANUP_HOURS = config('AUTOMATION_CLEANUP_HOURS', default=1, cast=int)
DEVICE_STATUS_SYNC_MINUTES = config('DEVICE_STATUS_SYNC_MINUTES', default=5, cast=int)

# System Settings
THREAD_POOL_MAX_WORKERS = config('THREAD_POOL_MAX_WORKERS', default=4, cast=int)

# SSE Settings
SSE_TIMEOUT_SECONDS = config('SSE_TIMEOUT_SECONDS', default=150, cast=int)
