# Generated by Django 5.1.6 on 2025-08-27 20:47

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ponds", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MQTTConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("broker_host", models.CharField(max_length=100)),
                ("broker_port", models.IntegerField()),
                ("is_connected", models.BooleanField(default=False)),
                ("connection_count", models.IntegerField(default=0)),
                ("client_id", models.CharField(max_length=100, unique=True)),
                ("username", models.CharField(blank=True, max_length=100, null=True)),
                ("connected_at", models.DateTimeField(blank=True, null=True)),
                ("disconnected_at", models.DateTimeField(blank=True, null=True)),
                ("last_heartbeat", models.DateTimeField(blank=True, null=True)),
                ("messages_sent", models.IntegerField(default=0)),
                ("messages_received", models.IntegerField(default=0)),
                ("errors_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["is_connected", "broker_host"],
                        name="mqtt_client_is_conn_44285a_idx",
                    ),
                    models.Index(
                        fields=["client_id"], name="mqtt_client_client__28776d_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DeviceStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ONLINE", "Online"),
                            ("OFFLINE", "Offline"),
                            ("ERROR", "Error"),
                            ("MAINTENANCE", "Maintenance"),
                        ],
                        default="OFFLINE",
                        max_length=20,
                    ),
                ),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
                ("connection_uptime", models.DurationField(blank=True, null=True)),
                (
                    "firmware_version",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "hardware_version",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("device_name", models.CharField(blank=True, max_length=50, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("wifi_ssid", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "wifi_signal_strength",
                    models.IntegerField(
                        blank=True,
                        help_text="WiFi signal strength in dBm",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-100),
                            django.core.validators.MaxValueValidator(0),
                        ],
                    ),
                ),
                (
                    "free_heap",
                    models.IntegerField(
                        blank=True, help_text="Free heap memory in bytes", null=True
                    ),
                ),
                (
                    "cpu_frequency",
                    models.IntegerField(
                        blank=True, help_text="CPU frequency in MHz", null=True
                    ),
                ),
                ("error_count", models.IntegerField(default=0)),
                ("last_error", models.TextField(blank=True, null=True)),
                ("last_error_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pond_pair",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_status",
                        to="ponds.pondpair",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["status", "last_seen"],
                        name="mqtt_client_status_462d98_idx",
                    ),
                    models.Index(
                        fields=["firmware_version"],
                        name="mqtt_client_firmwar_fca9b5_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MQTTMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(max_length=200)),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("PUBLISH", "Publish"),
                            ("SUBSCRIBE", "Subscribe"),
                            ("ACKNOWLEDGE", "Acknowledge"),
                            ("ERROR", "Error"),
                        ],
                        max_length=20,
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "payload_size",
                    models.IntegerField(help_text="Size of payload in bytes"),
                ),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("received_at", models.DateTimeField(blank=True, null=True)),
                ("processing_time", models.DurationField(blank=True, null=True)),
                ("message_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        blank=True,
                        help_text="ID to correlate related messages",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pond_pair",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mqtt_messages",
                        to="ponds.pondpair",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["pond_pair", "topic"],
                        name="mqtt_client_pond_pa_ac6fb2_idx",
                    ),
                    models.Index(
                        fields=["message_type", "success"],
                        name="mqtt_client_message_37cff4_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="mqtt_client_created_d74fc3_idx"
                    ),
                    models.Index(
                        fields=["message_id"], name="mqtt_client_message_5d9a18_idx"
                    ),
                    models.Index(
                        fields=["correlation_id"], name="mqtt_client_correla_8456aa_idx"
                    ),
                ],
            },
        ),
    ]
