# Generated by Django 5.1.6 on 2025-08-28 06:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mqtt_client", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MQTTConnection",
        ),
    ]
