# Generated by Django 5.1.6 on 2025-10-03 21:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="QRCodeGeneration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        help_text="Device ID (maximum 17 characters)",
                        max_length=17,
                        validators=[django.core.validators.MaxLengthValidator(17)],
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Optional notes about this QR code (maximum 500 characters)",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "qr_code_image",
                    models.ImageField(
                        blank=True,
                        help_text="Generated QR code image",
                        null=True,
                        upload_to="qr_generator/qr_codes/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "QR Code Generation",
                "verbose_name_plural": "QR Code Generations",
                "ordering": ["-created_at"],
            },
        ),
    ]
