# Generated by Django 5.1.6 on 2025-08-27 20:47

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ponds", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AutomationSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "automation_type",
                    models.CharField(
                        choices=[("FEED", "Feeding"), ("WATER", "Water Change")],
                        max_length=5,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("time", models.TimeField()),
                ("days", models.CharField(max_length=13)),
                (
                    "feed_amount",
                    models.FloatField(
                        blank=True, help_text="Feed amount in grams", null=True
                    ),
                ),
                (
                    "drain_water_level",
                    models.FloatField(
                        blank=True,
                        help_text="Water level to drain to (currently hardcoded to 0%)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "target_water_level",
                    models.FloatField(
                        blank=True,
                        help_text="Target water level percentage to refill to",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=3,
                        help_text="Priority level (1=highest, 5=lowest)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("last_execution", models.DateTimeField(blank=True, null=True)),
                ("next_execution", models.DateTimeField(blank=True, null=True)),
                ("execution_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pond",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="automation_schedules",
                        to="ponds.pond",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="automation_schedules_v2",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["priority", "time"],
            },
        ),
        migrations.CreateModel(
            name="AutomationExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "execution_type",
                    models.CharField(
                        choices=[("FEED", "Feeding"), ("WATER", "Water Change")],
                        max_length=20,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("FEED", "Feed"),
                            ("WATER_DRAIN", "Drain Water"),
                            ("WATER_FILL", "Fill Water"),
                            ("ALERT", "Send Alert"),
                            ("NOTIFICATION", "Send Notification"),
                            ("LOG", "Log Event"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("MANUAL_COMMAND", "Manual Command"),
                            ("EMERGENCY_WATER", "Emergency Water"),
                            ("SCHEDULED", "Scheduled"),
                            ("THRESHOLD", "Threshold"),
                        ],
                        default="THRESHOLD",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("EXECUTING", "Executing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("parameters", models.JSONField(blank=True, default=dict)),
                ("success", models.BooleanField(default=True)),
                ("result_message", models.TextField(blank=True, null=True)),
                ("error_details", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pond",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="automation_executions",
                        to="ponds.pond",
                    ),
                ),
                (
                    "threshold",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="automation_executions",
                        to="ponds.sensorthreshold",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="automation_executions_v2",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="executions",
                        to="automation.automationschedule",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DeviceCommand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "command_type",
                    models.CharField(
                        choices=[
                            ("FEED", "Feed Command"),
                            ("WATER_DRAIN", "Drain Water"),
                            ("WATER_FILL", "Fill Water"),
                            ("FIRMWARE_UPDATE", "Firmware Update"),
                            ("RESTART", "Device Restart"),
                            ("CONFIG_UPDATE", "Configuration Update"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SENT", "Sent"),
                            ("ACKNOWLEDGED", "Acknowledged"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("TIMEOUT", "Timeout"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("command_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("parameters", models.JSONField(blank=True, default=dict)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("timeout_seconds", models.IntegerField(default=10)),
                ("max_retries", models.IntegerField(default=3)),
                ("retry_count", models.IntegerField(default=0)),
                ("success", models.BooleanField(default=True)),
                ("result_message", models.TextField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, max_length=50, null=True)),
                ("error_details", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "automation_execution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="device_commands",
                        to="automation.automationexecution",
                    ),
                ),
                (
                    "pond",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_commands",
                        to="ponds.pond",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="device_commands_v2",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FeedEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField(help_text="Feed amount in kilograms")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "pond",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feed_events",
                        to="ponds.pond",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feed_events_v2",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="FeedStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stat_type",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("yearly", "Yearly"),
                        ],
                        max_length=10,
                    ),
                ),
                ("amount", models.FloatField(default=0.0)),
                (
                    "start_date",
                    models.DateField(
                        help_text="e.g. Sunday/Monday for weekly, Jan 1 for yearly"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pond",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feed_stats",
                        to="ponds.pond",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feed_stats_v2",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FeedStatHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stat_type",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("yearly", "Yearly"),
                        ],
                        max_length=10,
                    ),
                ),
                ("amount", models.FloatField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pond",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feed_stat_history",
                        to="ponds.pond",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feed_stat_history_v2",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="automationschedule",
            index=models.Index(
                fields=["pond", "automation_type"],
                name="automation__pond_id_0efdbe_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="automationschedule",
            index=models.Index(
                fields=["is_active", "next_execution"],
                name="automation__is_acti_623565_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="automationschedule",
            index=models.Index(
                fields=["priority", "next_execution"],
                name="automation__priorit_332de3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="automationexecution",
            index=models.Index(
                fields=["pond", "status"], name="automation__pond_id_ddcc06_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="automationexecution",
            index=models.Index(
                fields=["priority", "status"], name="automation__priorit_981e94_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="automationexecution",
            index=models.Index(
                fields=["execution_type", "status"],
                name="automation__executi_23a847_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="automationexecution",
            index=models.Index(
                fields=["scheduled_at"], name="automation__schedul_5836a5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="devicecommand",
            index=models.Index(
                fields=["pond", "status"], name="automation__pond_id_a344a6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="devicecommand",
            index=models.Index(
                fields=["command_type", "status"], name="automation__command_be9b4f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="devicecommand",
            index=models.Index(
                fields=["command_id"], name="automation__command_f271fc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="devicecommand",
            index=models.Index(
                fields=["created_at"], name="automation__created_3c34b2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feedevent",
            index=models.Index(
                fields=["user", "pond", "timestamp"],
                name="automation__user_id_7432ee_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="feedstat",
            index=models.Index(
                fields=["user", "pond", "stat_type", "start_date"],
                name="automation__user_id_b59f38_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="feedstat",
            unique_together={("user", "pond", "stat_type", "start_date")},
        ),
        migrations.AddIndex(
            model_name="feedstathistory",
            index=models.Index(
                fields=["user", "pond", "stat_type", "start_date", "end_date"],
                name="automation__user_id_e17812_idx",
            ),
        ),
    ]
