# Generated by Django 5.1.6 on 2025-10-04 22:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("automation", "0003_sync_with_database"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="feedstat",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="feedstat",
            name="pond",
        ),
        migrations.RemoveField(
            model_name="feedstat",
            name="user",
        ),
        migrations.RemoveField(
            model_name="feedstathistory",
            name="pond",
        ),
        migrations.RemoveField(
            model_name="feedstathistory",
            name="user",
        ),
        migrations.AlterField(
            model_name="automationschedule",
            name="action",
            field=models.CharField(
                choices=[
                    ("FEED", "Feed"),
                    ("WATER_DRAIN", "Drain Water"),
                    ("WATER_FILL", "Fill Water"),
                    ("WATER_FLUSH", "Flush Water"),
                    ("WATER_INLET_OPEN", "Open Water Inlet"),
                    ("WATER_INLET_CLOSE", "Close Water Inlet"),
                    ("WATER_OUTLET_OPEN", "Open Water Outlet"),
                    ("WATER_OUTLET_CLOSE", "Close Water Outlet"),
                    ("ALERT", "Send Alert"),
                    ("NOTIFICATION", "Send Notification"),
                    ("LOG", "Log Event"),
                ],
                help_text="Specific action to perform when this schedule executes",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="FeedEvent",
        ),
        migrations.DeleteModel(
            name="FeedStat",
        ),
        migrations.DeleteModel(
            name="FeedStatHistory",
        ),
    ]
